MOD_CONTROL_MISSING_ARG_1 = "`mod warn|mute|list`"
MOD_CONTROL_MISSING_ARG_2 = "`mod {} add|remove|rm|set`"
MOD_CONTROL_MISSING_ARG_3 = "`mod {} {} @mention`"
MOD_CONTROL_ROLE_SET_SUCCESSFULLY = "{} role set successfully."
MOD_CONTROL_ROLE_UNSET_SUCCESSFULLY = "{} role unset successfully."
MOD_CONTROL_ROLE_NOT_FOUND_IN_STORAGE = "That role wasn't added."

PUNISH_SUCCESS = "{} given."
PUNISH_MISSING_PUNISH_ROLE = "Role for {} a member does not exist or was never set."
PUNISH_USE = "`{} @mention`"
PUNISH_INVALID_TARGET = "You can't {} a {}."
PUNISH_WARN_SUCCESS = "Warned for 3 days."
PUNISH_DOUBLE_WARN = "Already had a warn, muting for 20 minutes."
PUNISH_MUTE_SUCCESS = "Muted for 20 minutes."

WORD_BAN_CONTROL_MISSING_ARG_1 = "`wordban list|toggle|add|remove|rm`"
WORD_BAN_CONTROL_MISSING_ARG_2 = "`wordban {} word`"
WORD_BAN_CONTROL_TOGGLE_MISSING_ARG = "`wordban toggle on|off`"
WORD_BAN_CONTROL_TOGGLE_ALREADY_ENABLED = "WordBan is already enabled."
WORD_BAN_CONTROL_TOGGLE_ENABLED = "WordBan enabled."
WORD_BAN_CONTROL_TOGGLE_ALREADY_DISABLED = "WordBan is already disabled."
WORD_BAN_CONTROL_TOGGLE_DISABLED = "WordBan disabled."
WORD_BAN_CONTROL_WORD_ADDED_TO_BAN = "Word ||{}|| added to ban list."
WORD_BAN_CONTROL_WORD_NOT_BANNED = "Word ||{}|| wasn't in the ban list."
WORD_BAN_CONTROL_WORD_REMOVED_FROM_BAN = "Word ||{}|| is no longer banned."


WORD_BAN_DELETE_WARN_SUCCESS = "Warned for 3 days, your message contained a banned word: ||{}||"
WORD_BAN_DELETE_DOUBLE_WARN_SUCCESS = "Muted for 20 mutes due to already having a warn, your message contained a " \
                                      "banned word: ||{}||"
