ADMIN_HELP = "This command "


WARN_HELP = "This command warns the given user for 3 days. Use `;warn @user` replacing `@user` by mentioning the user."
WARN_DEFAULT_REASON = "No reason given."
WARN_REASON = "{} Warned because: {}"
WARN_GIVEN = "3 day warn given."
WARN_DOUBLE = "Already had a warn, muted for 20 minutes."
WARN_DOUBLE_REASON = "{} Doubled warned because: {}"
WARN_MISSING_ROLE = "You lack the role or permission required to warn users."
WARN_CANT_WARN_WARNERS = "You can't warn the warners."
WARN_ROLE_MISSING = "The selected warn role is non-existent. Fix that by using `;warn_admin set_warn_role @role` replacing @role with mentioning the role."
WARN_MUTE_MISSING = "Can't do 2 warns -> mute due to mute not being assigned a role."

WARN_ADMIN_HELP = "You need to specify at least one argument, such as `add_warner_role`, `remove_warner_role`, `set_warn_role`, and `unset_warn_role`"
WARN_ADMIN_ADD_ROLE_HELP = "Adds a role to the list of roles allowed to warn people. @mention the role after the command to add it, like `;warn_admin add_warner_role @role`"
WARN_ADMIN_ADD_ROLE_SUCCESS = "Role added to list of warners."
WARN_ADMIN_REMOVE_ROLE_HELP = "Removes a role from the list of roles allowed to warn people. @mention the role after the command to remove it, like `;warn_admin add_warner_role @role`"
WARN_ADMIN_REMOVE_ROLE_SUCCESS = "Role removed from list of warners."
WARN_ADMIN_SET_ROLE_HELP = "Sets the role to warn users with. @mention the role after the command to set it, like `;warn_admin set_warn_role @role`"
WARN_ADMIN_SET_ROLE_SUCCESS = "Role to warn people with set successfully!"
WARN_ADMIN_UNSET_ROLE_SUCCESS = "Unset the role to warn people with successfully!"

MUTE_HELP = "This command mutes the given user for 20 minutes. Use `;mute @user` replacing `@user` by mentioning the user."
MUTE_DEFAULT_REASON = "No reason given."
MUTE_REASON = "{} muted because: {}"
MUTE_GIVEN = "20 minute warn given."
MUTE_MISSING_ROLE = "You lack the role or permission required to mute users."
MUTE_CANT_MUTE_MUTERS = "You can't mute the muters."
MUTE_ROLE_MISSING = "The selected mute role is non-existent. Fix taht by using `;mute_admin set_mute_role @role` replacing @role with mentioning the role."

MUTE_ADMIN_HELP = "Used to configure the mute feature. First level arguments can be: `add_muter_role`, `remove_muter_role`, `list_muter_roles`, `set_mute_role`, and `unset_mute_role`"
MUTE_ADMIN_ADD_ROLE_HELP = "Adds a role to the list of roles allowed to mute people. @mention the role after the command to add it, like `;mute_admin add_muter_role @role`"
MUTE_ADMIN_ADD_ROLE_SUCCESS = "Role added to list of muters successfully!"
MUTE_ADMIN_REMOVE_ROLE_HELP = "Removes a role from the list of roles allowed to mute people. @mention the role after the command to remove it, like `;warn_admin remove_muter_role @role`"
MUTE_ADMIN_REMOVE_ROLE_MISSING = "The given ID isn't in the list of muters."
MUTE_ADMIN_REMOVE_ROLE_SUCCESS = "Role removed from the list of muters successfully!"
MUTE_ADMIN_SET_ROLE_HELP = "Sets the role to mute users with. @mention the role after the command to set it, like `;mute_admin set_mute_role @role`"
MUTE_ADMIN_SET_ROLE_SUCCESS = "Role to mute people with set successfully!"
MUTE_ADMIN_UNSET_ROLE_SUCCESS = "Unset the role the mute people with successfully!"
