INVALID_COMMAND = "Invalid command given."

MMO_BRIEF = "User control panel for the MMO feature."
MMO_ENABLE_BRIEF = "Enables the user MMO features."
MMO_DISABLE_BRIEF = "Disables the user MMO features."
MMO_STATUS_BRIEF = "Shows the status of your character."
MMO_BATTLE_BRIEF = "Starts a 1v1 against an NPC around your level."
MMO_ATTACK_BRIEF = "[PH]NOT IMPLEMENTED."
MMO_CHAR_BRIEF = "Controls specific aspects of your character."
MMO_CHAR_CLASS_BRIEF = "Shows available and lets you switch classes."
MMO_CHAR_CLASS_LIST_BRIEF = "Shows available and unavailable classes."

MMOA_BRIEF = "Admin control panel for the MMO feature."
MMOA_ENABLE_BRIEF = "Enables the server-wide MMO features."
MMOA_DISABLE_BRIEF = "Disables the server-wide MMO features."
