INVALID_COMMAND = "Invalid command given."

MMO_BRIEF = "User control panel for the MMO feature."
MMO_ENABLE_BRIEF = "Enables the user MMO features."
MMO_DISABLE_BRIEF = "Disables the user MMO features."
MMO_STATUS_BRIEF = "Shows the status of your character."
MMO_BATTLE_BRIEF = "Starts a 1v1 against an NPC around your level."
MMO_ATTACK_BRIEF = "Changes your attack mid-battle."
MMO_CHAR_BRIEF = "Controls specific aspects of your character."
MMO_CHAR_CLASS_BRIEF = "Shows available and lets you switch classes."
MMO_CHAR_CLASS_LIST_BRIEF = "Shows available and unavailable classes."
MMO_CHAR_NAME_BRIEF = "Sets your characters name. Wrap in quotes for multi-word."
MMO_CHAR_ATTACK_BRIEF = "Sets the default attack to start battles with."
MMO_SPELLS_BRIEF = "Lists currently available spells."

MMOA_BRIEF = "Admin control panel for the MMO feature."
MMOA_ENABLE_BRIEF = "Enables the server-wide MMO features."
MMOA_DISABLE_BRIEF = "Disables the server-wide MMO features."
